### PR TITLE
Back to "Hackerspace" and New Navbar

### PR DESCRIPTION
**Pull request by ghost**
This PR includes the changes described below. Live changes can be viewed at https://ismandycoding.github.io/mandy-new-hsl/ :
* changing 'makerspace' back to 'hackerspace' from previous commit (originally in PR #169 )
* Some changes to markup to make it more semantic as it related to this PR (i.e. main element used instead of div for main portion of page content on index.html)
* ~~Removes dependency on local FontAwesome css files from index.html (planning to remove these completely in future updates).~~
* Remove old banner and add new navbar
* Responsive mobile version of navbar
* Navbar includes text links to 
  * Classes
  * Membership (The member site)
  * HeatSync Wiki
  * Google Discussion Group
 * Navbar includes a social icon links
   * Facebook group
   * Slack
   * Twitter
   * GitHub
   * Flickr

It currently uses the white version of the HeatSync logo from the [HeatSync Press Kit](https://wiki.heatsynclabs.org/wiki/Press_Kit). Future updates to the page are intended to use a version of the white logo with HeatSync orange inside the globe.
### 
Screenshots of changes below: 
**Mobile**
image
image

**Desktop**
image

### CODE REVIEW

**Comment by JulienTant** [comment]
Nice changes thanks! Few feedbacks:

image

On the right bellow the picture, "Fire Tornado" is way too big compared to the `>` icon
On the left there's a broken `spacer` image. Trying to point to `/img/pixel.gif`.

**Comment by ghost** [comment]
> Nice changes thanks! Few feedbacks:
> 
> image
> 
> On the right bellow the picture, "Fire Tornado" is way too big compared to the `>` icon On the left there's a broken `spacer` image. Trying to point to `/img/pixel.gif`.

Thank you for catching those! I initially thought the right-pointing chevron was another url resolving issue and didn't realize it was because I removed the font-awesome dependency, so I'll reserve removing that dependency for another PR for now.

**Review by JulienTant — APPROVED** [review]
LGTM

**Review by mwolfson — APPROVED** [review]
Ship it! Looks good when I review the code online, and I did review this at the site Mandy setup to checkout her changes (not sure how it reflects directly her).

**Pull request merged**
